# Generated by Django 5.2.8 on 2025-11-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(max_length=200)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='scraper.busquedascraper')),
            ],
        ),
    ]
